language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -e .
script:
  - python setup.py test
after_success:
  - coveralls
notifications:
  email:
    - sorin.otescu@gmail.com
