language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
before_install:
  - pip install coveralls
install:
  - pip install -e .
script:
  - python setup.py test
after_success:
  - if [[ $ENV == python=3.4* ]]; then
        coveralls;
    fi
notifications:
  email:
    - sorin.otescu@gmail.com

# Workarounds for Python 3.7, see https://github.com/travis-ci/travis-ci/issues/9815
sudo: required
dist: xenial
